using System;

namespace FMOD
{
	[Flags]
	public enum SYSTEM_CALLBACK_TYPE : uint
	{
		DEVICELISTCHANGED = 0x1,
		DEVICELOST = 0x2,
		MEMORYALLOCATIONFAILED = 0x4,
		THREADCREATED = 0x8,
		BADDSPCONNECTION = 0x10,
		PREMIX = 0x20,
		POSTMIX = 0x40,
		ERROR = 0x80,
		MIDMIX = 0x100,
		THREADDESTROYED = 0x200,
		PREUPDATE = 0x400,
		POSTUPDATE = 0x800,
		RECORDLISTCHANGED = 0x1000,
		ALL = uint.MaxValue
	}
}
